version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "8000:80" # пробрасываем порт из контейнера на локальную машину

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # пробрасываем порт из контейнера на локальную машину
