version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        env_file:
            - ../../../Music/nsk/backend/.env
        environment:
            - APP_KEY=${APP_KEY}
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge

