version: '3'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - .:/app
            - Z:\:/fileserver/ERP_file
        env_file:
            - .env
        environment:
            - APP_KEY=${APP_KEY}
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge

