version: "3"
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        environment:
            - APP_KEY=${APP_KEY}
        volumes:
            - /mnt/serverdata:/app/ERP_FILES
        networks:
            - mynetwork
networks:
    mynetwork:
        driver: bridge
